# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
tone_instructions: ""
early_access: true
enable_free_tier: true
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  high_level_summary_in_walkthrough: true
  auto_title_placeholder: "@coderabbitai"
  auto_title_instructions: ""
  review_status: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: true
  changed_files_summary: true
  sequence_diagrams: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: false
  suggested_reviewers: true
  auto_assign_reviewers: false
  poem: true
  path_filters:
    - "!docs/**/*.js"
    - "!docs/**/*.css"
    - "!docs/**/*.html"
    - "!htmlFiles/**/*.html"
  path_instructions:
    - path: "basilisk/src/"
      instructions: "the basilisk folder contains the upstream dependency. you should not review what is inside the basilisk folder, but use the files in basilisk/src/ for context and review other files in the rest of the repository"
    - path: "_layouts/**/*.html"
      instructions: "This is the layout file for the website. Any changes to the layout should be made in this file."
    - path: ".github/scripts/*"
      instructions: "This is the folder for the GitHub actions scripts."
  abort_on_close: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
  tools:
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      level: "default"
    ast-grep:
      essential_rules: true
    shellcheck:
      enabled: true
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    biome:
      enabled: true
    hadolint:
      enabled: true
    swiftlint:
      enabled: true
    phpstan:
      enabled: true
      level: "default"
    golangci-lint:
      enabled: true
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    detekt:
      enabled: true
    eslint:
      enabled: true
    rubocop:
      enabled: true
    buf:
      enabled: true
    regal:
      enabled: true
    actionlint:
      enabled: true
    pmd:
      enabled: true
    cppcheck:
      enabled: true
    semgrep:
      enabled: true
    circleci:
      enabled: true
    sqlfluff:
      enabled: true
    prismaLint:
      enabled: true
    oxc:
      enabled: true
  finishing_touches:
    docstrings:
      enabled: true
chat:
  auto_reply: true
  create_issues: true
  integrations:
    jira:
      usage: "disabled"
    linear:
      usage: "disabled"
knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  learnings:
    scope: "auto"
  issues:
    scope: "auto"
  jira:
    usage: "disabled"
  linear:
    usage: "disabled"
  pull_requests:
    scope: "auto"
code_generation:
  docstrings:
    language: "en-US"