#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>

/**
 * @brief Reads the next identifier or token from standard input into a buffer.
 *
 * Skips whitespace and comments, handles quoted character tokens, and reads identifiers consisting of letters and underscores. Stores the result in the provided buffer and returns the character that terminated the read.
 *
 * @param buf Buffer to store the read identifier or token. Must be large enough to hold the result.
 * @return int The character that terminated the read, or EOF if end of input is reached.
 */
int read_identifier (char * buf)
{
  int c;
  while ((c = getchar()) != EOF && strchr (" \n\t", c));
  if (c == '%')
    return c;
  if (c == '{')
    while ((c = getchar()) != EOF && c != '}');
  if (c == '/') {
    c = getchar();
    if (c == '*')
      while (((c = getchar()) != EOF && c != '*') ||
	     ((c = getchar()) != EOF && c != '/'));
    else {
      assert (c == '/');
      while ((c = getchar()) != EOF && c != '\n');
    }
  }
  if (c == '\'') {
    *buf++ = c;
    c = getchar();
    *buf++ = c;
    c = getchar();
    *buf++ = c;
    assert (c == '\'');
    c = getchar();
  }
  else
    while (c != EOF && (c == '_' ||
			(c >= 'a' && c <= 'z') ||
			(c >= 'A' && c <= 'Z'))) {
      *buf++ = c;
      c = getchar();
    }
  *buf = '\0';
  return c;
}

/**
 * @brief Reads grammar rules from standard input and generates C code for syntax tree node matching.
 *
 * Processes input until a double percent sign (`%%`) is encountered, then parses grammar rules specifying parent and child symbols. For each rule, outputs C code that checks if a node's symbol and its children match the specified grammar structure. The generated code uses logical conditions to verify symbol matches and child node arrangements, supporting both named symbols and quoted character tokens.
 *
 * The output is printed to standard output and is intended for use in parser or AST matcher implementations.
 *
 * @return int Returns 0 upon successful completion.
 */
int main()
{
  printf ("/* Automatically generated by grammar.c */\n");
  int c;
  while ((c = getchar()) != EOF)
    if (c == '%') {
      c = getchar();
      if (c == '%')
	break;
    }
  do {
    char parent[100], child[100];
    c = read_identifier (parent);
    if (c == '%')
      break;
    if (parent[0] != '\0' && strcmp (parent, "type_not_specified")) {
      printf ("if (n->sym == sym_%s)\n"
	      "  return (", parent);
      int m = 0;
      do {	
	int n = 0;
	if (m > 0)
	  printf (" ||\n          ");
	printf ("(");
	do {
	  c = read_identifier (child);
	  if (child[0] != '\0' && strcmp (child, "type_not_specified")) {
	    if (n > 0)
	      printf (" &&\n           ");
	    printf ("n->child[%d] && n->child[%d]->sym == %s%s%s",
		    n, n, child[0] == '\'' ? "token_symbol(" : "sym_",
		    child, child[0] == '\'' ? ")" : "");
	    n++;
	  }
	} while (c != '|' && c != ';');
	printf (" && !n->child[%d]", n);
	printf (")");
	m++;
      } while (c != ';');
      printf (");\n");
    }
  } while (c != EOF);
}
